
print("Arithmatic Operator *************************")
number1 = int(input("Enter first number : "))
number2 = int(input("Enter second number : "))
print(number1+number2)
print(number1-number2)
print(number1*number2)
print(number1/number2)
print(number1%number2)
print(number1//number2)
print(number1**2)
print(2**3)
print("Assignment Operator *************************")